// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/kichikawa/ent/runtime.go

const (
	Version = "v0.10.1-0.20220204204617-770e4d24e9b1"           // Version of ent codegen.
	Sum     = "h1:1zC2H8NxqPAlXQY2XAgGvXpCc3IJjsMUC/X+JqhWOuk=" // Sum of ent codegen.
)
