// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
	"github.com/kichikawa/ent"
)

type NewTodo struct {
	Text   string `json:"text"`
	UserID UserId `json:"userId"`
}

type Todo struct {
	ID        TodoId         `json:"id"`
	Text      graphql.Upload `json:"text"`
	Done      bool           `json:"done"`
	Dones     bool           `json:"dones"`
	User      *ent.User      `json:"user"`
	Pet       *ent.Pet       `json:"pet"`
	CreatedAt *string        `json:"createdAt"`
}

type Signal string

const (
	SignalRed    Signal = "RED"
	SignalYellow Signal = "YELLOW"
	SignalGreen  Signal = "GREEN"
)

var AllSignal = []Signal{
	SignalRed,
	SignalYellow,
	SignalGreen,
}

func (e Signal) IsValid() bool {
	switch e {
	case SignalRed, SignalYellow, SignalGreen:
		return true
	}
	return false
}

func (e Signal) String() string {
	return string(e)
}

func (e *Signal) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Signal(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Signal", str)
	}
	return nil
}

func (e Signal) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type UserStatus string

const (
	UserStatusInProgress UserStatus = "IN_PROGRESS"
	UserStatusCompleted  UserStatus = "COMPLETED"
)

var AllUserStatus = []UserStatus{
	UserStatusInProgress,
	UserStatusCompleted,
}

func (e UserStatus) IsValid() bool {
	switch e {
	case UserStatusInProgress, UserStatusCompleted:
		return true
	}
	return false
}

func (e UserStatus) String() string {
	return string(e)
}

func (e *UserStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserStatus", str)
	}
	return nil
}

func (e UserStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
