// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/kichikawa/ent/schema/property"
)

type CreateUserInput struct {
	Email    property.UserEmail `json:"email"`
	Password string             `json:"password"`
	Age      int                `json:"age"`
}
