// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/kichikawa/ent/good"
)

// Good is the model entity for the Good schema.
type Good struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// TweetID holds the value of the "tweet_id" field.
	TweetID  uuid.UUID `json:"tweet_id,omitempty"`
	tweet_id *uuid.UUID
	user_id  *uuid.UUID
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Good) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case good.FieldCreatedAt, good.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case good.FieldID, good.FieldUserID, good.FieldTweetID:
			values[i] = new(uuid.UUID)
		case good.ForeignKeys[0]: // tweet_id
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case good.ForeignKeys[1]: // user_id
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			return nil, fmt.Errorf("unexpected column %q for type Good", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Good fields.
func (_go *Good) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case good.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_go.ID = *value
			}
		case good.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_go.CreatedAt = value.Time
			}
		case good.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_go.UpdatedAt = value.Time
			}
		case good.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_go.UserID = *value
			}
		case good.FieldTweetID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tweet_id", values[i])
			} else if value != nil {
				_go.TweetID = *value
			}
		case good.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field tweet_id", values[i])
			} else if value.Valid {
				_go.tweet_id = new(uuid.UUID)
				*_go.tweet_id = *value.S.(*uuid.UUID)
			}
		case good.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_go.user_id = new(uuid.UUID)
				*_go.user_id = *value.S.(*uuid.UUID)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Good.
// Note that you need to call Good.Unwrap() before calling this method if this Good
// was returned from a transaction, and the transaction was committed or rolled back.
func (_go *Good) Update() *GoodUpdateOne {
	return (&GoodClient{config: _go.config}).UpdateOne(_go)
}

// Unwrap unwraps the Good entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_go *Good) Unwrap() *Good {
	tx, ok := _go.config.driver.(*txDriver)
	if !ok {
		panic("ent: Good is not a transactional entity")
	}
	_go.config.driver = tx.drv
	return _go
}

// String implements the fmt.Stringer.
func (_go *Good) String() string {
	var builder strings.Builder
	builder.WriteString("Good(")
	builder.WriteString(fmt.Sprintf("id=%v", _go.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(_go.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(_go.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", user_id=")
	builder.WriteString(fmt.Sprintf("%v", _go.UserID))
	builder.WriteString(", tweet_id=")
	builder.WriteString(fmt.Sprintf("%v", _go.TweetID))
	builder.WriteByte(')')
	return builder.String()
}

// Goods is a parsable slice of Good.
type Goods []*Good

func (_go Goods) config(cfg config) {
	for _i := range _go {
		_go[_i].config = cfg
	}
}
