// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Follow is the predicate function for follow builders.
type Follow func(*sql.Selector)

// Good is the predicate function for good builders.
type Good func(*sql.Selector)

// RefreshToken is the predicate function for refreshtoken builders.
type RefreshToken func(*sql.Selector)

// Tweet is the predicate function for tweet builders.
type Tweet func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
